pipeline {
    agent {
        node {
            label "Workstation1"
        }
    }

    options {
        ansiColor('xterm')
    }

    stages{

        stage('Apply'){
            steps{
                sh '''
                  cd jenkins-ip-update
                  terraform init
                  terraform apply -auto-approve
                '''
            }
        }
    }
    post {
      always {
        cleanWs()
      }
    }
}
